version: "3.8"
services:
  server:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: raw_layer
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
    restart: no
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
